
import json
import os
from datetime import datetime

def generate_report():
    print("Generating report...")
    
    # Load Metrics
    try:
        with open("metrics.json", "r") as f:
            metrics = json.load(f)
    except FileNotFoundError:
        print("Error: metrics.json not found. Run train_model.py first.")
        return

    # Load Feature Names
    try:
        with open("feature_names.json", "r") as f:
            features = json.load(f)
    except FileNotFoundError:
        features = ["Unknown"]

    # Check for plots
    plots = {
        "Histograms": "eda_histograms.png",
        "Correlation Matrix": "eda_correlation.png",
        "Quality Distribution": "eda_quality_dist.png"
    }
    
    existing_plots = {name: path for name, path in plots.items() if os.path.exists(path)}

    # Generate Markdown Content
    report_content = f"""# Wine Quality Prediction Project Report
**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 1. Model Performance
The Random Forest model (HistGradientBoostingRegressor) achieved the following performance on the test set:

| Metric | Value |
| :--- | :--- |
| **R² Score** | {metrics.get('r2', 'N/A'):.4f} |
| **RMSE** | {metrics.get('rmse', 'N/A'):.4f} |
| **MAE** | {metrics.get('mae', 'N/A'):.4f} |

## 2. Features Used
The model utilized the following {len(features)} input features:
"""
    for feature in features:
        report_content += f"- {feature}\n"

    report_content += "\n## 3. Exploratory Data Analysis\n"
    
    if existing_plots:
        for name, path in existing_plots.items():
            report_content += f"### {name}\n![{name}]({path})\n\n"
    else:
        report_content += "> ⚠️ No EDA plots found. Please run `eda_plots.py`.\n"

    report_content += "\n---\n*Report generated by VinoVeritas Automation System*"

    # Write to file
    with open("Wine_Quality_Report.md", "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print("Report generated: Wine_Quality_Report.md")

if __name__ == "__main__":
    generate_report()
